version: '3.8'

services:
    discord-bot:
        build: .
        container_name: discord-secretary
        restart: unless-stopped
        volumes:
            - ./config:/app/config
        environment:
            - NODE_ENV=production
